version: '3.8'
services:
  nginx:
    image: nginx:1.19.9-alpine
    depends_on:
      - keycloak
    volumes:
      - ./files/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    networks:
      - backend-network
  db:
    image: postgres:13.2
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend-network
  keycloak:
    image: jboss/keycloak:12.0.4
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: ${DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      # KEYCLOAK_LOGLEVEL: DEBUG
      PROXY_ADDRESS_FORWARDING: "true" # important for reverse proxy
    volumes:
      - ./files/realm-export.json:/tmp/realm-export.json
    depends_on:
      - db
    expose:
      - 8080
    networks: 
      - backend-network
volumes:
  postgresdata: {}
networks:
  backend-network:
    driver: bridge
    name: backend_network