version: '3'
services:
  app_db:
    image: mariadb:10.5.9
    restart: always
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=dbpassword
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - backend-network
  app:
    depends_on:
      - app_db
    build:
      context: ./..
      dockerfile: docker/Dockerfile
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://app_db:3306/appdb
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: password
      KEYCLOAK_SERVER_AUTH_URL: http://localhost:8080/auth # tells keycloak to check JWT issuer against this value
      KEYCLOAK_PROXY_URL: http://iam:8080/auth # tells keycloak to proxy calls to keycloak running in docker
    restart: on-failure
    networks:
      - backend-network
volumes:
  mysqldata: { }
networks: 
  backend-network:
    name: backend_network