version: '3'
services:
  # Identity Access Management
  iam_db:
    image: postgres
    volumes:
      - ./iam_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  iam:
    image: jboss/keycloak:12.0.4
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: iam_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - iam_db
    ports:
      - 8080:8080
  # App
  app_db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=dbpassword
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
  app:
    depends_on:
      - app_db
      - iam
    build:
      context: ./..
      dockerfile: docker/Dockerfile
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://app_database:3306/appdb
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: password
      KEYCLOAK_SERVER_AUTH_URL: http://iamserver:8080/auth
